### ISSUE TITLE
Occasional plotting issues due to shape mismatch

### ISSUE THREAD

**Issue by elma16** [elma16/SeaIceSim#3]
`ValueError: x and y must have same first dimension, but have shapes (10,) and (11,)`

The issue here is that this is not a consistent error.

**Comment by MetallicSquid** [comment]
Good luck with that.

**Comment by MetallicSquid** [comment]
In TensorFlow there are .reshape and .resize commands that can sometimes help with that. Size mismatch errors are generally indicative of an error with the inputs to the function anyway.

Sometimes .transpose works too (rows -> cols, cols -> rows)
